name: 'St Lukes, Wimbledon Park'
favicon: null
layout_spectrum: 0.79461
typography_spectrum: 1
title: "St Luke's, Wimbledon Park.   Sunday services : 1030 & 6pm.  Do join us."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a723f'
    - '#050407'
    - '#caa8d3'
    - '#714d99'
  brandStrength: 0.3923992950003594
  lightness: 0.11892973305657506
  saturation: 0.4375
  rhythmicContrast: 0.27432836685329676
purpose: []
